env: dev
spring:
  application:
    name: order
  jpa:
    database: oracle
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.230:1521:KWW
    username: testdatabase
    password: sa
  rabbitmq:
    host: 192.168.9.72
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.9.72
    port: 6379
# 访问如：    ip+端口/order-dev.yml
